# Generated by Django 2.1.1 on 2018-09-09 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.TextField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('WIDOW', 'Widow'), ('WIDOWER', 'Widower'), ('DIVORCED', 'Divorced')], max_length=10)),
                ('place_of_birth', models.CharField(max_length=45)),
                ('nationality_at_birth', django_countries.fields.CountryField(max_length=2)),
                ('present_nationality', django_countries.fields.CountryField(max_length=2)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('permanent_address', models.CharField(max_length=50)),
                ('permanent_addr_tel', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128)),
                ('present_address', models.CharField(blank=True, max_length=50, null=True)),
                ('present_addr_tel', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128)),
                ('permanent_addr_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('office_tel', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128)),
                ('office_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-birthdate'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('employer', models.CharField(max_length=100)),
                ('employer_address', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=25)),
                ('supervisor_name', models.CharField(blank=True, max_length=45, null=True)),
                ('exact_job_title_held', models.CharField(max_length=45)),
                ('no_of_employees_supervised', models.PositiveIntegerField(blank=True, null=True)),
                ('kind_of_employees_supervised', models.CharField(blank=True, max_length=25, null=True)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_of_duties', models.TextField()),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('annual_salary_starting', models.DecimalField(decimal_places=0, max_digits=9)),
                ('annual_salary_final', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
            options={
                'ordering': ['-ending_date'],
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['field'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('city_published', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('full_name', models.CharField(max_length=50)),
                ('full_address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('business_or_occupation', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('international_organization', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
